name: mircade
version: git
summary: Example Mir confined desktop
description: This example can be used as a guide
confinement: strict
grade: stable
base: core20

apps:
  mircade:
    command-chain:
      - bin/wayland-if-possible
    command: bin/egmde-launch
    plugs:
      - wayland
      - x11
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

  daemon:
    command-chain:
      - bin/nested-start
    command: bin/egmde-launch
    daemon: simple
    restart-condition: always
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse
    plugs:
      - wayland

plugs:
  opengl:
  audio-playback:
  network-bind:
  login-session-control:
  joystick:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH:    $SNAP/graphics/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  LIBGL_DRIVERS_PATH: $SNAP/graphics/dri
  LIBVA_DRIVERS_PATH: $SNAP/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/graphics/glvnd/egl_vendor.d
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config

layout:
  /usr/share/applications:
    bind: $SNAP/usr/share/applications
  /usr/share/crawl:
    bind: $SNAP/usr/share/crawl
  /usr/share/starfighter:
    bind: $SNAP/usr/share/starfighter
  /usr/share/games:
    bind: $SNAP/usr/share/games
  /usr/games:
    bind: $SNAP/usr/games
  /usr/lib/games:
    bind: $SNAP/usr/lib/games
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mir
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/share/libdrm:  # Needed by mesa-core20 on AMD GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:  # Used by mesa-core20 for app specific workarounds
    bind: $SNAP/graphics/drirc.d

parts:
  neverball:
    plugin: nil
    stage-packages:
      - neverball

  neverputt:
    plugin: nil
    stage-packages:
      - neverputt

  starfighter:
    plugin: nil
    stage-packages:
      - starfighter

  supertux:
    plugin: nil
    stage-packages:
      - supertux

  supertuxkart:
    plugin: nil
    override-build: |
      snapcraftctl build
      sed --in-place s'!^Exec=supertuxkart$!Exec=supertuxkart --fullscreen!' $SNAPCRAFT_PART_INSTALL/usr/share/applications/supertuxkart.desktop
    stage-packages:
      - supertuxkart

  crawl-tiles:
    plugin: nil
    stage-packages:
      - crawl-tiles

# Weird cursor - seems to track motion with incorrect scale
#  caveexpress:
#    plugin: nil
#    stage-packages:
#      - caveexpress

  7kaa:
    plugin: nil
    stage-packages:
      - 7kaa

  config:
    plugin: dump
    source: config

  setup-scripts:
    plugin: dump
    source: setup-scripts

  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      sudo apt --assume-yes install libmiral-dev
      snapcraftctl pull

  egmde:
    after: [ppa-setup]
    source: https://github.com/AlanGriffiths/egmde.git
    source-branch: mircade
    plugin: cmake
    build-packages:
      - build-essential
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
      - libwayland-dev
      - libxkbcommon-dev
      - g++
    stage-packages:
      - libmiral4
      - mir-graphics-drivers-desktop
      - fonts-freefont-ttf
    stage:
      - -usr/share/wayland-sessions/egmde.desktop
      - -bin/egmde-launch

  misc:
    plugin: nil
    stage-packages:
      - libaudio2
      - libxcb1
      - libpulse0
      - libsndfile1
      - libasyncns0
      - liblua5.2-0
      - libslang2
      - libgpm2
      - libgtk3-nocsd0
      - dbus
      - libusb-1.0-0
      - libglu1-mesa

  sdl2:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  cleanup:
    after:
      - neverball
      - neverputt
      - starfighter
      - supertux
      - supertuxkart
      - crawl-tiles
      - 7kaa
      - config
      - setup-scripts
      - egmde
      - misc
      - sdl2
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
