name: mircade
version: git
summary: Example Mir confined desktop
description: This example can be used as a guide
confinement: strict
grade: devel
base: core18

apps:
  mircade:
    command: egmde-launch
    plugs:
      - login-session-control
      - x11
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

plugs:
  opengl:
  audio-playback:
  hardware-observe: # This allows some UDEV access neverputt wants
  network-bind:

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio:${SNAP}/usr/lib/libreoffice/program/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/samba
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_DATA_DIRS:   $SNAP/usr/share
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep for Qt wayland
  QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/
  QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/platforms/
  QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
  QTCHOOSER_NO_GLOBAL_DIR: 1
  QT_SELECT: snappy-qt5

layout:
  /usr/share/starfighter:
    bind: $SNAP/usr/share/starfighter
  /usr/share/games:
    bind: $SNAP/usr/share/games
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mir
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

parts:
  games:
    plugin: nil
    stage-packages:
      # SDL & working
      - neverball
      - neverputt
      - starfighter

  config:
    plugin: dump
    source: config

  egmde:
    source: .
    plugin: cmake-with-ppa
    ppa: mir-team/dev
    build-packages:
      - pkg-config
      - libmiral-dev
      - libboost-filesystem-dev
      - libfreetype6-dev
      - libwayland-dev
      - libxkbcommon-dev
    stage-packages:
      - fonts-freefont-ttf
      - mir-graphics-drivers-desktop
      - libmiral3
    stage:
      - -usr/share/wayland-sessions/egmde.desktop

  misc:
    plugin: nil
    stage-packages:
      - libxcb1
      - libpulse0
      - libsndfile1
      - libasyncns0
      - liblua5.2-0
      - libslang2
      - libgpm2
      - libgtk3-nocsd0
      - dbus
      - libusb-1.0-0

  sdl2:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa
